
background = 0xCC2E3440
base = 0xCC3B4252
text = 0xFFD8DEE9
alternate_base = 0xCC434C5E
bright_text = 0xFF81A1C1
accent = 0xFF88C0D0
accent_secondary = 0xFF81A1C1
rounding_large = 8
rounding_small = 4
